server {
    listen 4242;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 100000000;

    # 1. / must answer to GET request ONLY
    location / {
        allow_methods GET;
        index index.html;
    }

    # 2. /directory/ must answer to GET, root is YoupiBanane, index is youpi.bad_extension
    location /directory {
        allow_methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
    }

    # 3. /post_body must answer anything to POST request with a maxBody of 100
    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
    }

    # 4. Any file with .bla as extension must execute cgi_test via POST
    location .bla {
        allow_methods POST GET;
        cgi_path ./cgi_test;
    }
}